import type { QuestionDefinitionInput } from "@/domain/check-in/check-in";

export const SYNTHETIC_CHECK_IN_NOTICE = "PLANTILLA SINTÉTICA / NO APROBADA / NO USO CLÍNICO";

export const SYNTHETIC_CHECK_IN_QUESTIONS = [
  {
    questionKey: "sleep",
    position: 1,
    type: "SCALE",
    prompt: "Ejemplo sintético: ¿cómo valorarías tu sueño reciente?",
    required: true,
    scaleMinimum: 0,
    scaleMaximum: 4,
    scaleMinimumLabel: "Muy difícil",
    scaleMaximumLabel: "Muy reparador",
  },
  {
    questionKey: "anxiety",
    position: 2,
    type: "SCALE",
    prompt: "Ejemplo sintético: ¿qué intensidad de ansiedad has notado?",
    required: true,
    scaleMinimum: 0,
    scaleMaximum: 4,
    scaleMinimumLabel: "Ninguna",
    scaleMaximumLabel: "Muy intensa",
  },
  {
    questionKey: "mood",
    position: 3,
    type: "SCALE",
    prompt: "Ejemplo sintético: ¿cómo describirías tu ánimo?",
    required: true,
    scaleMinimum: 0,
    scaleMaximum: 4,
    scaleMinimumLabel: "Muy bajo",
    scaleMaximumLabel: "Muy bueno",
  },
  {
    questionKey: "adherence",
    position: 4,
    type: "YES_NO",
    prompt: "Ejemplo sintético: ¿has seguido el plan acordado con tu equipo?",
    required: true,
  },
  {
    questionKey: "substance-use",
    position: 5,
    type: "SINGLE_CHOICE",
    prompt: "Ejemplo sintético: selecciona la opción que mejor describa consumo reciente.",
    required: true,
    options: ["Sin consumo", "Consumo registrado", "Prefiero no contestar"],
  },
  {
    questionKey: "self-harm-ideation",
    position: 6,
    type: "YES_NO",
    prompt: "Ejemplo sintético: ¿has tenido pensamientos de hacerte daño?",
    required: true,
  },
  {
    questionKey: "irritability",
    position: 7,
    type: "SCALE",
    prompt: "Ejemplo sintético: ¿qué nivel de irritabilidad has notado?",
    required: true,
    scaleMinimum: 0,
    scaleMaximum: 4,
    scaleMinimumLabel: "Ninguno",
    scaleMaximumLabel: "Muy alto",
  },
  {
    questionKey: "family-conflict",
    position: 8,
    type: "RESTRICTED_SHORT_TEXT",
    prompt: "Ejemplo sintético: si quieres, describe brevemente algún conflicto familiar.",
    required: false,
    maximumTextLength: 160,
  },
] as const satisfies readonly QuestionDefinitionInput[];
