import type { Role } from "@/domain/auth/role";

export const AUDIT_ACTIONS = [
  "DEMO_LOGIN",
  "SESSION_LOGOUT",
  "ROLE_ASSIGNED",
  "ROLE_REVOKED",
  "CRITICAL_MUTATION",
  "LEGAL_RECORD_CREATED",
  "LEGAL_RECORD_REVOKED",
  "POLICY_VERSION_CREATED",
  "EPISODE_CREATED",
  "EPISODE_TRANSITIONED",
  "SAFETY_PLAN_VERSION_CREATED",
  "SAFETY_PLAN_VERSION_ACTIVATED",
  "SAFETY_PLAN_VERSION_INVALIDATED",
  "CHECK_IN_PROTOCOL_VERSION_CREATED",
  "CHECK_IN_ASSIGNMENTS_CREATED",
  "CHECK_IN_RESPONSE_RECORDED",
  "CHECK_IN_NON_RESPONSE_RECORDED",
  "RULE_VERSION_CREATED",
  "RULE_VERSION_APPROVED",
  "RULE_VERSION_ACTIVATED",
  "RULE_EVALUATED",
  "ALERT_CREATED",
  "ALERT_REVIEWED",
  "ALERT_ACTION_RECORDED",
  "ALERT_RESOLVED",
  "ALERT_DISMISSED",
  "TASK_CREATED",
  "TASK_ASSIGNED",
  "TASK_REASSIGNED",
  "TASK_CONTACT_ATTEMPT_RECORDED",
  "TASK_NOTE_RECORDED",
  "TASK_RESOLVED",
  "CAREGIVER_INVITATION_CREATED",
  "CAREGIVER_INVITATION_ACCEPTED",
  "CAREGIVER_SCOPE_CHANGED",
  "CAREGIVER_ACCESS_REVOKED",
  "CAREGIVER_OBSERVATION_RECORDED",
  "CAREGIVER_SESSION_LOGGED_OUT",
  "HOME_SAFETY_VERSION_CREATED",
  "SBAR_PREVIEW_GENERATED",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
export type AuditOutcome = "SUCCESS" | "DENIED" | "FAILURE";

export interface NewAuditEvent {
  readonly actorUserId: string | null;
  readonly actorRole: Role | null;
  readonly action: AuditAction;
  readonly resourceType: string;
  readonly resourceId: string | null;
  readonly outcome: AuditOutcome;
  readonly correlationId: string;
  readonly createdAt: Date;
}
